name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ruff
        run: pip install ruff

      - name: Run static analysis (Ruff)
        run: ruff check . --select=F401,F841,E --ignore=E501


      - name: Type checking (Mypy)
        run: mypy .

      - name: Lint with Pylint
        run: |
          pip install pylint
          pylint $(git ls-files '*.py')

      - name: Check if tests exist
        id: test-check
        run: |
          if [ -d "tests" ] && ls tests/test_*.py 1> /dev/null 2>&1; then
            echo "has_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_tests=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run tests if any
        if: steps.test-check.outputs.has_tests == 'true'
        run: |
          pip install pytest pytest-cov
          pytest --cov=app --cov-report=html tests/

      - name: Upload coverage report
        if: steps.test-check.outputs.has_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
